name: O.C. CryoSport
favicon: null
layout_spectrum: 0.74918
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b1464'
    - '#d0ecf2'
    - '#26a9e0'
    - '#254c80'
    - '#a5bdbd'
  brandStrength: 0.875
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 1
purpose:
  - name: awareness
    item: 1e514ad2-1ee5-4b6c-8b1f-c3d6c04970c3
    url: null
